import { Geist } from "next/font/google";
import "./globals.css";
import SidebarTables from "@/components/SidebarTables";

const geist = Geist({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geist.className} antialiased dark`}>
        <div className="flex">
          <SidebarTables />
          <div className="w-4/5 min-h-screen">{children}</div>
        </div>
      </body>
    </html>
  );
}
